### ISSUE TITLE
No code available

### ISSUE THREAD

**Issue by Utopiah** [LokiResearch/Chameleon#1]
From "Bringing Interactivity to Research Papers and Presentations with Chameleon" and noticing "Chameleon currently runs on macOS and Linux" and "Source code available at ns.inria.fr/loki/chameleon" but the redirection here shows nothing.

**Comment by m-damien** [comment]
Hello Fabien,

Thank you for your interest in Chameleon!
We are in the process of pushing the code to the repository, we just need a couple more days (the associated paper was published a week ago); the code will definitely be pushed before the end of the month.

Thank you for your patience,
Damien

**Comment by m-damien** [comment]
The code is now pushed.
